### ISSUE TITLE
Food for OKC Python Wednesday Oct 12

### ISSUE THREAD

**Issue by mmattice** [techlahoma/techlahoma#142]
group: okcpython
food type: ?
guests RSVPed: 10
meeting date: Thursday, Oct 12 2016 at 11:30 AM
location: Prototek

**Comment by seejessicacode** [comment]
I've been working on automatically creating these issues as Meetup events are created, It's still a good idea for all UG leaders to check in to make sure a food issue has been created.

Duplicate issue #134

**Comment by amandaharlin** [comment]
got 12 boxed lunches, a gourmet veggie club sandwich, 12 choc cookies, and 6 raisin cookies. you'll have to get the drinks like usual, since only pizza places seem to deliver 12 liters.

<img width="639" alt="screen shot 2016-10-12 at 10 15 35 am" src="https://cloud.githubusercontent.com/assets/716644/19315859/fa98deb0-9064-11e6-95ac-49328f9b7c8b.png">
